---
- name: discover network
  hosts: all
  connection: local
  tasks:
    - name: get interface brief
      cisco.ios.ios_command:
        commands:
          - show ip interface brief | e una
      register: interfaces
    - name: print results
      debug:
        msg: "{{ interfaces.stdout[0] }}"
